# Generated by Django 5.1.4 on 2025-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_icon', models.ImageField(upload_to='img')),
                ('app_name', models.CharField(db_column='name', max_length=100)),
                ('app_link', models.URLField(db_column='link', max_length=100)),
                ('app_category', models.CharField(db_column='category', max_length=100)),
                ('sub_category', models.CharField(db_column='subcategory', max_length=100)),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'admin_app',
            },
        ),
    ]
